config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  
  get "tasks/new", to: "tasks#new", as: 'new_task'
  
  get "task", to: "tasks#index"
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: 'task'
  get "tasks/:id/edit", o: "tasks#edit", as: "edit_task"
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy", as: "delete_task"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @tasks = Task.all
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.new(task_params)
        if @task.save
            redirect_to task_path(@task)
        else
            render 'new'
        end
    end

    def edit
        @task = Task.find(params[:id])
    end

    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        redirect_to task_path
    end

    def update
        @task = Task.find(params[:id])
        if @task.update(rask_params)
            redirect_to task_path(@task)
        else
            render 'edit'
        end
    end

    private

    def task_params
        params.require(:task).permit(:title, :details, :completed)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :compleed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>
<%= render 'form', task: @task %>
<%= link_to 'Back to Task',
task_path(@task) %>

app/views/tasks/index.html.erb
<h2>All tasks</h2>
<ul>
  <% @tasks.each do |task| %>
    <li><%= task.title %></li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h2>New Task</h2>
<%= render 'form', task: @task %>
<%= link_to 'Back to Tasks', tasks_path %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<h2><%= @task.details %></h2>
<p>Complete: <%= @task.completed ? 'Yes' : 'No' %></p>
<%= link_to 'Back to Tasks', task_path %>